name: pytest

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10' ]
        os: [ ubuntu, macos, windows ]

    name: PY${{ matrix.python-version }} ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Poetry
      run: pip install poetry
    - name: Install dependencies
      run: poetry install
    - name: Test with pytest
      run: poetry run python -m pytest --cov=hikari_clusters/ --cov-report=xml
    - name: Upload to CodeCov
      uses: codecov/codecov-action@v2
